apiVersion: batch/v1
kind: Job
metadata:
  name: transpose-${FILE}
spec:
  backoffLimit: 0
  completions: 1
  template:
    metadata:
      labels:
        k8s-app: transpose-${FILE}
    spec:
      restartPolicy: Never
      containers:
      - name: transpose-${FILE}
        image: jmlehrer/transpose:latest
        command: ["stdbuf", "-i0", "-o0", "-e0", "bash", "-c"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        args: [
          "gunzip ${FILE}.tsv.gz && \
          python transpose.py -file ${FILE}.tsv -chunksize=200 -sep='\t' && \
          ./combine.sh ${FILE}_T && \
          python upload_helper.py -file ${FILE}_T.csv"]
        resources:
          limits:
            memory: 100Gi
            cpu: "24"
          requests:
            memory: 32Gi
            cpu: "8"
        volumeMounts:
        - name: ephemeral
          mountPath: "/data"
      volumes:
      - name: ephemeral
        emptyDir: {}